### ISSUE TITLE
How to only crawl latest post?

### ISSUE THREAD

**Issue by null15** [proxycrawl/proxycrawl-python#10]
Hey,

how to only get the latest content of the last post?

**Comment by crawlbase** [comment]
@null15 this depends on the website that you are crawling. You will get all the content from the page and then you will have to parse the content via an HTML parsing module or library. For python you can use [html.parser](https://docs.python.org/3/library/html.parser.html)

As this is more an issue related to a website than to the library itself, I'm closing the issue. Please contact directly our support team for [further assistance here](https://proxycrawl.com/dashboard/support).
