### ISSUE TITLE
Possible issue when options argument is None

### ISSUE THREAD

**Issue by taktak-dev** [proxycrawl/proxycrawl-python#4]
I just tried the latest version (2.0.0) of the API by copying the usage example for a get in the readme file  : 

```
#Python3
from proxycrawl.proxycrawl_api import ProxyCrawlAPI
api = ProxyCrawlAPI({ 'token': 'my_token' })
response = api.get('https://www.facebook.com/britneyspears')
```

and I got an error because the code tries to call a get function on the options argument which is None here as it was not given explicitly. 

In the case I call get as follows by giving an empty dict for options, I don't get the error: 

`response = api.get('https://www.facebook.com/britneyspears',  {})`

I did not have this behavior with the previous version of the API (1.1.1). This causes that I cannot upgrade to 2.0.0 and keep my existing code as it is.

Regards

**Comment by crawlbase** [comment]
Hello @taktak-dev thanks for the report. This should be now fixed in version 2.0.1
