### ISSUE TITLE
Token issue

### ISSUE THREAD

**Issue by seanng123456789** [proxycrawl/proxycrawl-python#7]
Hi,

I am sorry I am a newbie on data crawling. And my first mission is facebook cralwer for public page without login. However, even I modify the user agent and a few ip rotation each page. The public page still occur the login require before I can see the public page(I check log in my program). This rate is up to 50% around. It's very annoying.
I saw some blog refer to this framework for easily crawling. So I wanna ask a few questions. 
Do I need facebook api token for using this lib? If no, what is the proxy_token in the example. 

Thank you so much.

**Comment by crawlbase** [comment]
Hello @seanng123456789 you do not need the Facebook API to use our library.
You can [get your token from here](https://proxycrawl.com/signup)

Last but not least, I'll be closing this issue as it's not an issue with the library itself. If you have more questions you can directly [ask our crawling support team here](https://proxycrawl.com/dashboard/support), which will happily assist you.
