### ISSUE TITLE
ScraperAPI Error

### ISSUE THREAD

**Issue by Deskola** [proxycrawl/proxycrawl-python#8]
Am getting this error bellow when I run the code in your git hub repo readme 
http_method = options.pop('HTTP_METHOD') if options.has_key('HTTP_METHOD') else None
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by Deskola** [comment]
Installed python 3.9
Error raised in base_api.py file line 49
Never mind, i solved it by replacing has_key with __contains__.

**Comment by crawlbase** [comment]
Thank you for reporting, this is now fixed and released https://pypi.org/project/proxycrawl/
